### ISSUE TITLE
開発環境のセットアップ手順についてドキュメントを用意する

### ISSUE THREAD

**Issue by Seasawher** [lean-ja/mathematics_in_lean_source#14]
あるいは，devcontainer や gitpod でセットアップをする手段を提供する．

**Comment by Seasawher** [comment]
@s-taiga @Taka0007  GitPod で開いたときに自動的にプレビューが立ち上がるようにしてみました.

**Comment by s-taiga** [comment]
@Seasawher 
ありがとうございます！

**Comment by Taka0007** [comment]
@Seasawher 
そんな便利な機能も実装できるんですか…！
ありがとうございます！！
